require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

$FirebaseSDKVersion = '7.7.0'

target 'ListingApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'Google-Mobile-Ads-SDK'

  use_unimodules!
end
